name: 'Tokei Badge'
description: 'Make a "line of codes" badge for your repo.'
runs:
  using: "composite"
  steps:
    - run: echo $PWD
      shell: bash
    - run: ls ${{ github.action_path }}
      shell: bash
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cd ${{ github.action_path }} && /home/runner/.cargo/bin/cargo build --release --all-features
      shell: bash
    - run: ${{ github.action_path }}/target/release/tokei_badge
      shell: bash
