on: [push]

name: Make the Badge

jobs:
  make-badge:
    name: Make the Badge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Generate the "Lines of Code" Badge
        uses: lightyears1998/tokei-badge@master
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
